server:
  port: 8090
  use-forward-headers: true
spring:
  devtools:
    enabled: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  freemarker:
    template-loader-path:
      - classpath:/templates
    cache: false
    check-template-location: true
    charset: utf-8
    settings:
      classic_compatible: true #处理空值
      template_exception_handler: rethrow
      template_update_delay: 0
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
      auto_import: /utils.ftl as utils
  flyway:
    enabled: false
    baseline-on-migrate: true
    encoding: UTF-8
    locations: classpath:scripts/migration
  datasource:
    #schema: classpath*:scripts/schema.sql
    #continue-on-error: false
    #sql-script-encoding: utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.delpast.com:3306/db_blog?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: xiangge
    password: Spectator#0320
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: file:/home/blog/resources/static
#安全框架
shiro:
  web:
    enabled: true
  annotations:
    enabled: false
  loginUrl: /login
  successUrl: /index
  unauthorizedUrl: /error/reject.html
  sessionManager:
    cookie:
      maxAge: 604800
  rememberMeManager:
    cookie:
      maxAge: 604800
logging:
  file: ./logs/default.log
  level:
    root: info
    org.springframework: info
    org.hibernate: info

# site.options.theme: classic
site:
  version: 1.0.0
  location: ${user.dir}
  controls:
    # 注册开关
    register: true
    # 注册开启邮箱验证
    register_email_validate: true
    # 发布文章开关
    post: true
    # 评论开关
    comment: true
  options:
    storage_max_width: 800
    storage_limit_size: 20
    editor: markdown
    thumbnail_channel_size: 200x112
    thumbnail_post_size: 360x200